-- ============================================================
-- E-Commerce Database System
-- 03_views.sql — Views
-- ============================================================

-- ----------------------------------------
-- VIEW 1: Customer Order Summary
-- Shows each customer with their total orders and total spending
-- ----------------------------------------
CREATE OR REPLACE VIEW vw_customer_order_summary AS
SELECT c.customer_id,
       c.first_name || ' ' || c.last_name AS customer_name,
       c.email,
       c.city,
       COUNT(o.order_id) AS total_orders,
       NVL(SUM(o.total_amount), 0) AS total_spent
FROM customers c
LEFT OUTER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.email, c.city;

-- ----------------------------------------
-- VIEW 2: Product Catalog with Category
-- Shows product details along with their category name
-- ----------------------------------------
CREATE OR REPLACE VIEW vw_product_catalog AS
SELECT p.product_id,
       p.product_name,
       c.category_name,
       p.price,
       p.stock_quantity,
       p.date_added,
       p.description AS product_description
FROM products p
JOIN categories c ON p.category_id = c.category_id;

-- ----------------------------------------
-- VIEW 3: Order Details (Full Breakdown)
-- Shows each order with customer info, items, and product names
-- ----------------------------------------
CREATE OR REPLACE VIEW vw_order_details AS
SELECT o.order_id,
       o.order_date,
       c.first_name || ' ' || c.last_name AS customer_name,
       p.product_name,
       cat.category_name,
       oi.quantity,
       oi.unit_price,
       oi.subtotal,
       o.order_status
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
JOIN categories cat ON p.category_id = cat.category_id;

-- ----------------------------------------
-- VIEW 4: Revenue per Category
-- Shows total revenue generated by each product category
-- ----------------------------------------
CREATE OR REPLACE VIEW vw_category_revenue AS
SELECT cat.category_id,
       cat.category_name,
       COUNT(DISTINCT oi.item_id) AS items_sold,
       NVL(SUM(oi.subtotal), 0) AS total_revenue
FROM categories cat
LEFT OUTER JOIN products p ON cat.category_id = p.category_id
LEFT OUTER JOIN order_items oi ON p.product_id = oi.product_id
LEFT OUTER JOIN orders o ON oi.order_id = o.order_id AND o.order_status <> 'Cancelled'
GROUP BY cat.category_id, cat.category_name;

-- ----------------------------------------
-- VIEW 5: Shipping Tracker
-- Shows order shipping status with customer and delivery info
-- ----------------------------------------
CREATE OR REPLACE VIEW vw_shipping_tracker AS
SELECT s.shipping_id,
       s.tracking_number,
       o.order_id,
       c.first_name || ' ' || c.last_name AS customer_name,
       s.shipping_address,
       s.shipping_date,
       s.delivery_date,
       s.shipping_status,
       o.total_amount
FROM shipping s
JOIN orders o ON s.order_id = o.order_id
JOIN customers c ON o.customer_id = c.customer_id;
